"""
Imagen Service.

Image generation using Google Gemini Pro Image API.
"""
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from app.config import Config


class ImagenService:
    """
    Service class for image generation via Gemini Pro Image API.
    """

    MODEL_ID = "gemini-3-pro-image-preview"
    DEFAULT_ASPECT_RATIO = "16:9"

    def __init__(self):
        """Initialize with lazy-loaded client."""
        self._client = None

    def _get_client(self):
        """
        Get or create the Google GenAI client.

        Returns:
            Google GenAI client instance

        Raises:
            ValueError: If GEMINI_API_KEY is not configured
        """
        if self._client is None:
            if not Config.GEMINI_API_KEY:
                raise ValueError("GEMINI_API_KEY not found in environment")

            from google import genai
            self._client = genai.Client(api_key=Config.GEMINI_API_KEY)

        return self._client

    def generate_image(
        self,
        prompt: str,
        output_dir: Path,
        filename_prefix: str = "image",
        aspect_ratio: str = None
    ) -> Dict[str, Any]:
        """
        Generate a single image from a text prompt.

        Args:
            prompt: The text prompt describing the image
            output_dir: Directory to save the image
            filename_prefix: Prefix for the filename
            aspect_ratio: Image aspect ratio (e.g., "16:9", "1:1")

        Returns:
            Dict with success status and image info
        """
        if not prompt or not prompt.strip():
            return {
                "success": False,
                "error": "No prompt provided"
            }

        aspect_ratio = aspect_ratio or self.DEFAULT_ASPECT_RATIO

        try:
            client = self._get_client()
            from google.genai import types

            print(f"[Imagen] Generating image...")
            print(f"  Prompt: {prompt[:80]}...")

            output_dir.mkdir(parents=True, exist_ok=True)

            # Generate image
            response = client.models.generate_content(
                model=self.MODEL_ID,
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_modalities=["TEXT", "IMAGE"],
                )
            )

            # Extract and save image
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{filename_prefix}_{timestamp}.png"
            filepath = output_dir / filename

            for part in response.candidates[0].content.parts:
                if hasattr(part, "inline_data") and part.inline_data:
                    # Save image data
                    with open(filepath, "wb") as f:
                        f.write(part.inline_data.data)

                    print(f"  Saved: {filename}")

                    return {
                        "success": True,
                        "filename": filename,
                        "path": str(filepath),
                    }

            return {
                "success": False,
                "error": "No image generated by the API"
            }

        except ValueError as e:
            return {
                "success": False,
                "error": str(e)
            }
        except Exception as e:
            print(f"[Imagen] Error: {e}")
            return {
                "success": False,
                "error": f"Image generation failed: {str(e)}"
            }

    def is_configured(self) -> bool:
        """Check if Gemini API key is configured."""
        return bool(Config.GEMINI_API_KEY)


# Singleton instance
imagen_service = ImagenService()
